# -*- coding: utf-8 -*-
"""Copy of QHUP_hologram_simulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/154A5WjsRFXQmOti0r1S5Qo-63JfjchD_
"""

# Commented out IPython magic to ensure Python compatibility.
# ===== DL-QHUP: single-shot hologram sim + QHUPnet + rich exports (ZIP + auto-download) =====
# Colab setup (installs)
try:
    import google.colab
    IN_COLAB = True
except Exception:
    IN_COLAB = False
if IN_COLAB:
#     %pip -q install torchmetrics pytorch-msssim imageio --upgrade

# --- Imports & setup ---
import os, math, random, csv, json, shutil
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torchvision import datasets, transforms

from torchmetrics.image.ssim import StructuralSimilarityIndexMeasure
from pytorch_msssim import SSIM
from dataclasses import dataclass
from pathlib import Path
from matplotlib.backends.backend_pdf import PdfPages

if IN_COLAB:
    from google.colab import files  # for auto-download

# Reproducibility
torch.manual_seed(42); np.random.seed(42); random.seed(42)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# --- Paths for exports ---
OUT = Path("exports")
(OUT/"samples").mkdir(parents=True, exist_ok=True)           # 4-up panel PNGs
(OUT/"arrays").mkdir(parents=True, exist_ok=True)            # NPY arrays
(OUT/"figs").mkdir(parents=True, exist_ok=True)              # plots + gallery PDF
(OUT/"metrics").mkdir(parents=True, exist_ok=True)           # CSV metrics
(OUT/"samples_individual").mkdir(parents=True, exist_ok=True)# individual PNGs (holo/amp/phase)
(OUT/"montages").mkdir(parents=True, exist_ok=True)

# --- QHUP-like simulator (shape-safe) ---
@dataclass
class QHUPParams:
    r_p: float = 1.0; r_s: float = 1.0; r_i: float = 1.0
    gamma_mag: float = 0.6
    phi_p: float = 0.0; delta_phi: float = 0.0
    read_noise_std: float = 0.01; background_level: float = 0.0

def simulate_qhup_hologram(amplitude, phase, params: QHUPParams):
    """
    amplitude, phase: [B,1,H,W] tensors; returns [B,1,H,W]
    """
    r_p, r_s, r_i = params.r_p, params.r_s, params.r_i
    gamma = params.gamma_mag
    phi = phase - params.phi_p + params.delta_phi
    base = r_p**2 + r_s**2
    inter = 2.0 * r_p * r_s * r_i * gamma * torch.cos(phi)
    I = base + amplitude * inter
    if params.background_level != 0.0:
        I = I + params.background_level
    if params.read_noise_std > 0.0:
        I = I + torch.randn_like(I) * params.read_noise_std
    # Normalize per-frame to [0,1]
    I = I - I.amin(dim=(-2,-1), keepdim=True)
    I = I / (I.amax(dim=(-2,-1), keepdim=True) + 1e-8)
    return I

def random_params(visibility: float, read_noise_std: float, background_level: float):
    gamma_mag = float(np.clip(visibility, 0.0, 1.0))
    return QHUPParams(
        gamma_mag=gamma_mag,
        delta_phi=float(np.random.uniform(-math.pi, math.pi)),
        read_noise_std=read_noise_std,
        background_level=background_level
    )

def make_random_amplitude_phase(B, H, W):
    amp = torch.rand(B,1,H,W)
    phase = torch.randn(B,1,H,W)
    k = 9
    phase = F.avg_pool2d(phase, k, stride=k//2, padding=0)
    phase = F.interpolate(phase, size=(H,W), mode="bilinear", align_corners=False)
    phase = math.pi * torch.tanh(phase)
    return amp.clamp(0,1), phase

# --- Dataset: MNIST amplitude + synthetic phase ---
class QHUPMnist(Dataset):
    def __init__(self, train=True, size=64, n_samples=20000):
        self.size=size; self.train=train; self.n_samples=n_samples
        self.tf = transforms.Compose([transforms.Resize((size,size)), transforms.ToTensor()])
        self.mnist = datasets.MNIST(root="./data", train=train, download=True, transform=self.tf)
    def __len__(self): return self.n_samples
    def _random_phase(self, H, W):
        p = torch.randn(1,1,H,W)
        p = F.avg_pool2d(p, 9, stride=4)
        p = F.interpolate(p, size=(H,W), mode="bilinear", align_corners=False)
        return math.pi * torch.tanh(p)
    def __getitem__(self, idx):
        img,_ = self.mnist[random.randrange(0, len(self.mnist))]
        amp = img                                  # [1,H,W]
        phase = self._random_phase(self.size,self.size)  # [1,1,H,W]
        vis = np.random.uniform(0.2, 0.9)
        read_noise = np.random.uniform(0.0, 0.03)
        bg = np.random.uniform(0.0, 0.05)
        params = random_params(vis, read_noise, bg)
        holo = simulate_qhup_hologram(amp.unsqueeze(0), phase, params)[0]  # [1,H,W]
        return {"holo":holo, "amp":amp, "phase":phase.squeeze(0)}

# Quick sanity sample
tmp = QHUPMnist(train=True, size=64, n_samples=8)[0]
print({k: tuple(v.shape) for k,v in tmp.items()})

# --- Model: Dense blocks + ASPP + Cat.Conv. ---
class DenseBlock(nn.Module):
    def __init__(self, in_ch, growth_rate=32, layers=3):
        super().__init__(); mods=[]; ch=in_ch
        for _ in range(layers):
            mods += [nn.Conv2d(ch, growth_rate, 3, padding=1, bias=False),
                     nn.BatchNorm2d(growth_rate), nn.ReLU(inplace=True)]
            ch += growth_rate
        self.layers = nn.ModuleList(mods); self.layers_n = layers
    def forward(self, x):
        feats=[x]
        for i in range(self.layers_n):
            conv,bn,act = self.layers[3*i:3*i+3]
            out = act(bn(conv(torch.cat(feats, dim=1)))); feats.append(out)
        return torch.cat(feats, dim=1)

class ASPP(nn.Module):
    def __init__(self, in_ch, out_ch, rates=(1,6,12,18)):
        super().__init__()
        self.branches = nn.ModuleList([nn.Conv2d(in_ch, out_ch, 1, padding=0, bias=False)] +
                                      [nn.Conv2d(in_ch, out_ch, 3, padding=r, dilation=r, bias=False) for r in rates[1:]])
        self.proj = nn.Conv2d(out_ch*len(self.branches), out_ch, 1, bias=False)
        self.bn = nn.BatchNorm2d(out_ch); self.act = nn.ReLU(inplace=True)
    def forward(self, x):
        y = torch.cat([b(x) for b in self.branches], dim=1)
        return self.act(self.bn(self.proj(y)))

class QHUPNet(nn.Module):
    def __init__(self, width=32):
        super().__init__()
        self.stem = nn.Sequential(nn.Conv2d(1, width, 3, padding=1, bias=False),
                                  nn.BatchNorm2d(width), nn.ReLU(inplace=True))
        self.db1 = DenseBlock(width, growth_rate=width//2, layers=3); ch1 = width + 3*(width//2)
        self.down1 = nn.Conv2d(ch1, width*2, 3, stride=2, padding=1, bias=False)
        self.db2 = DenseBlock(width*2, growth_rate=width//2, layers=3); ch2 = width*2 + 3*(width//2)
        self.down2 = nn.Conv2d(ch2, width*4, 3, stride=2, padding=1, bias=False)
        self.db3 = DenseBlock(width*4, growth_rate=width//2, layers=3); ch3 = width*4 + 3*(width//2)
        self.aspp = ASPP(ch3, width*4)
        self.up1 = nn.ConvTranspose2d(width*4, width*2, 2, stride=2)
        self.dec1 = nn.Sequential(nn.Conv2d(width*2 + ch2, width*2, 3, padding=1, bias=False),
                                  nn.BatchNorm2d(width*2), nn.ReLU(inplace=True))
        self.up2 = nn.ConvTranspose2d(width*2, width, 2, stride=2)
        self.dec2 = nn.Sequential(nn.Conv2d(width + ch1, width, 3, padding=1, bias=False),
                                  nn.BatchNorm2d(width), nn.ReLU(inplace=True))
        self.head_amp = nn.Sequential(nn.Conv2d(width, 1, 1), nn.Sigmoid())
        self.head_phase = nn.Conv2d(width, 1, 1)
    def forward(self, x):
        x0=self.stem(x); e1=self.db1(x0); x1=self.down1(e1); e2=self.db2(x1); x2=self.down2(e2)
        b=self.db3(x2); b=self.aspp(b); d1=self.up1(b); d1=torch.cat([d1,e2],dim=1); d1=self.dec1(d1)
        d2=self.up2(d1); d2=torch.cat([d2,e1],dim=1); d2=self.dec2(d2)
        amp=self.head_amp(d2); phase=math.pi*torch.tanh(self.head_phase(d2))
        return amp, phase

model = QHUPNet(width=32).to(device)
print("Model params (M):", sum(p.numel() for p in model.parameters())/1e6)

# --- Losses & metrics ---
class PhaseL1(nn.Module):
    def forward(self, pred, target):
        diff = torch.atan2(torch.sin(pred - target), torch.cos(pred - target))
        return diff.abs().mean()

ssim_torchmetrics = StructuralSimilarityIndexMeasure(data_range=1.0).to(device)  # keep metric on GPU/CPU with tensors
ssim_loss = SSIM(data_range=1.0, size_average=True, channel=1)

def amp_loss_fn(pred_amp, gt_amp):
    return (1.0 - ssim_loss(pred_amp, gt_amp)) + F.l1_loss(pred_amp, gt_amp)

phase_loss_fn = PhaseL1()

# --- Training/eval setup ---
BATCH = 32
train_ds = QHUPMnist(train=True, size=64, n_samples=4000)
val_ds   = QHUPMnist(train=False, size=64, n_samples=512)
train_dl = DataLoader(train_ds, batch_size=BATCH, shuffle=True, num_workers=2 if torch.cuda.is_available() else 0)
val_dl   = DataLoader(val_ds, batch_size=BATCH, shuffle=False, num_workers=2 if torch.cuda.is_available() else 0)

optimizer = torch.optim.AdamW(model.parameters(), lr=2e-3, weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=10)
EPOCHS = 5  # bump to 50-100 for stronger results

train_log = []  # to save CSV/JSON later

def run_epoch(loader, train=True):
    model.train(train)
    total_loss = 0.0
    total_ssim = 0.0
    n = 0
    for batch in loader:
        holo = batch["holo"].to(device)
        if holo.ndim == 5:  # defensive: [B,1,1,H,W] -> [B,1,H,W]
            holo = holo.squeeze(1)
        gt_amp = batch["amp"].to(device)
        gt_phase = batch["phase"].to(device)

        if train:
            optimizer.zero_grad()
        pred_amp, pred_phase = model(holo)
        loss = amp_loss_fn(pred_amp, gt_amp) + 0.5 * phase_loss_fn(pred_phase, gt_phase)
        if train:
            loss.backward()
            optimizer.step()

        with torch.no_grad():
            ssim_val = ssim_torchmetrics(pred_amp, gt_amp)

        bs = holo.size(0)
        total_loss += float(loss.item()) * bs
        total_ssim += float(ssim_val.item()) * bs
        n += bs

    return total_loss / n, total_ssim / n

best_val = float("inf")
for ep in range(1, EPOCHS+1):
    tr_loss, tr_ssim = run_epoch(train_dl, train=True)
    val_loss, val_ssim = run_epoch(val_dl, train=False)
    scheduler.step()

    train_log.append({"epoch": ep, "train_loss": tr_loss, "train_ssim": tr_ssim,
                      "val_loss": val_loss, "val_ssim": val_ssim, "lr": scheduler.get_last_lr()[0]})
    print(f"Epoch {ep:02d} | train loss {tr_loss:.4f} SSIM {tr_ssim:.3f} | val loss {val_loss:.4f} SSIM {val_ssim:.3f}")

    if val_loss < best_val:
        best_val = val_loss
        torch.save(model.state_dict(), OUT/"qhupnet_best.pt")

print("Saved best model ->", OUT/"qhupnet_best.pt")

# Save training log as CSV & JSON
with open(OUT/"training_log.csv", "w", newline="") as f:
    w = csv.DictWriter(f, fieldnames=list(train_log[0].keys()))
    w.writeheader(); w.writerows(train_log)
with open(OUT/"training_log.json", "w") as f:
    json.dump(train_log, f, indent=2)

# --- Student-friendly exports ---
def save_individual_png(path, arr, title=None):
    plt.figure(figsize=(3,3))
    plt.imshow(arr)
    if title: plt.title(title)
    plt.axis('off')
    plt.tight_layout()
    plt.savefig(path, dpi=150)
    plt.close()

def save_panel_png(path, holo, amp_gt, amp_pred, phase_pred, suptitle=None):
    fig, axes = plt.subplots(1, 4, figsize=(12,3))
    axes[0].imshow(holo); axes[0].set_title("Hologram"); axes[0].axis('off')
    axes[1].imshow(amp_gt); axes[1].set_title("GT amplitude"); axes[1].axis('off')
    axes[2].imshow(amp_pred); axes[2].set_title("Pred amplitude"); axes[2].axis('off')
    axes[3].imshow(phase_pred); axes[3].set_title("Pred phase"); axes[3].axis('off')
    if suptitle: fig.suptitle(suptitle)
    plt.tight_layout()
    plt.savefig(path, dpi=150)
    plt.close(fig)

@torch.no_grad()
def save_samples_for_teaching(ds, n=9, out_img_dir=OUT/"samples", out_arr_dir=OUT/"arrays",
                              out_individual=OUT/"samples_individual", gallery_pdf=OUT/"figs/teaching_gallery.pdf"):
    model.eval()
    idxs = [random.randrange(0, len(ds)) for _ in range(n)]
    # Save chosen indices
    with open(OUT/"metrics/sample_indices.csv", "w", newline="") as f:
        w = csv.writer(f); w.writerow(["sample_index_in_dataset"]); w.writerows([[ix] for ix in idxs])

    with PdfPages(gallery_pdf) as pdf:
        for i, idx in enumerate(idxs):
            sample = ds[idx]
            holo_t = sample["holo"].unsqueeze(0).to(device)
            if holo_t.ndim == 5: holo_t = holo_t.squeeze(1)
            amp_gt_t = sample["amp"]
            amp_pred_t, phase_pred_t = model(holo_t)
            # numpy arrays
            holo = holo_t.squeeze(0).cpu().numpy()[0]
            amp_gt = amp_gt_t.cpu().numpy()[0]
            amp_pred = amp_pred_t.squeeze(0).cpu().numpy()[0]
            phase_pred = phase_pred_t.squeeze(0).cpu().numpy()[0]
            # Save arrays
            np.save(out_arr_dir/f"holo_{i}.npy", holo)
            np.save(out_arr_dir/f"amp_gt_{i}.npy", amp_gt)
            np.save(out_arr_dir/f"amp_pred_{i}.npy", amp_pred)
            np.save(out_arr_dir/f"phase_pred_{i}.npy", phase_pred)
            # Save individual PNGs
            save_individual_png(out_individual/f"holo_{i}.png", holo, "Hologram")
            save_individual_png(out_individual/f"amp_gt_{i}.png", amp_gt, "Ground truth amplitude")
            save_individual_png(out_individual/f"amp_pred_{i}.png", amp_pred, "Predicted amplitude")
            save_individual_png(out_individual/f"phase_pred_{i}.png", phase_pred, "Predicted phase")
            # Save 4-up panel PNG
            panel_path = out_img_dir/f"sample_{i}.png"
            save_panel_png(panel_path, holo, amp_gt, amp_pred, phase_pred, suptitle=f"Sample {i}")
            # Add to PDF
            fig, axes = plt.subplots(1,4, figsize=(12,3))
            for ax, img, title in zip(axes, [holo, amp_gt, amp_pred, phase_pred],
                                      ["Hologram","GT amplitude","Pred amplitude","Pred phase"]):
                ax.imshow(img); ax.set_title(title); ax.axis('off')
            plt.tight_layout()
            pdf.savefig(fig)
            plt.close(fig)

save_samples_for_teaching(val_ds, n=9)
print("Saved student-friendly images (individual + panels) and gallery PDF.")

# --- Robust montage builder (handles grayscale, RGBA) ---
def _load_rgb_image(path):
    import imageio.v2 as imageio
    im = imageio.imread(str(path))
    # Grayscale -> RGB
    if im.ndim == 2:
        im = np.stack([im]*3, axis=-1)
    # RGBA -> RGB
    elif im.ndim == 3 and im.shape[2] == 4:
        im = im[..., :3]
    # Normalize to uint8 if needed
    if im.dtype != np.uint8:
        im = (255 * (im - im.min()) / (im.ptp() + 1e-8)).astype(np.uint8)
    return im

def make_montage(panel_paths, cols=3, save_path=OUT/"montages/montage_3x3.png"):
    import imageio.v2 as imageio
    imgs = [_load_rgb_image(p) for p in panel_paths]
    rows = (len(imgs) + cols - 1) // cols
    h = max(im.shape[0] for im in imgs)
    w = max(im.shape[1] for im in imgs)
    montage = np.ones((rows*h, cols*w, 3), dtype=np.uint8) * 255
    for i, im in enumerate(imgs):
        r, c = divmod(i, cols)
        canvas = np.ones((h, w, 3), dtype=np.uint8) * 255
        ih, iw = im.shape[:2]
        canvas[:ih, :iw, :] = im
        montage[r*h:(r+1)*h, c*w:(c+1)*w, :] = canvas
    imageio.imwrite(str(save_path), montage)
    return save_path

# Build montage from the 4-up panels
panel_paths = sorted((OUT/"samples").glob("sample_*.png"))[:9]
if panel_paths:
    montage_path = make_montage(panel_paths, cols=3, save_path=OUT/"montages/montage_3x3.png")
    print("Saved montage:", montage_path)

# --- Visibility robustness sweep (CSV + plot PNG) ---
@torch.no_grad()
def evaluate_vs_visibility(num=200, vis_list=(0.2,0.4,0.6,0.8)):
    model.eval(); results=[]
    for vis in vis_list:
        amps, phases, holos = [], [], []
        for _ in range(num):
            amp, phase = make_random_amplitude_phase(1, 64, 64)
            params = random_params(visibility=vis, read_noise_std=0.02, background_level=0.02)
            holo = simulate_qhup_hologram(amp, phase, params)
            amps.append(amp); phases.append(phase); holos.append(holo)
        amp = torch.cat(amps,0).to(device)
        phase = torch.cat(phases,0).to(device)
        holo = torch.cat(holos,0).to(device)
        if holo.ndim == 5: holo = holo.squeeze(1)
        pred_amp, pred_phase = model(holo)
        loss = (amp_loss_fn(pred_amp, amp) + 0.5*phase_loss_fn(pred_phase, phase)).item()
        ssim_val = ssim_torchmetrics(pred_amp, amp).item()
        results.append({"visibility": vis, "loss": loss, "ssim_amp": ssim_val})
        print(f"vis={vis:.1f}  loss={loss:.4f}  SSIM={ssim_val:.3f}")
    return results

vis_results = evaluate_vs_visibility()
# Save CSV + plot
with open(OUT/"metrics/visibility_sweep.csv", "w", newline="") as f:
    w = csv.DictWriter(f, fieldnames=["visibility","loss","ssim_amp"])
    w.writeheader(); w.writerows(vis_results)

plt.figure(figsize=(5,4))
xs = [r["visibility"] for r in vis_results]
ys = [r["ssim_amp"] for r in vis_results]
plt.plot(xs, ys, marker='o')
plt.xlabel("Visibility (proxy gamma)"); plt.ylabel("SSIM (amplitude)")
plt.title("Reconstruction robustness vs visibility"); plt.grid(True)
plt.tight_layout(); plt.savefig(OUT/"figs/visibility_sweep.png", dpi=150); plt.close()
print("Saved visibility sweep CSV and PNG to:", OUT/"metrics", "and", OUT/"figs")

# --- Resolution sweep (CSV + plot PNG) ---
def make_sine_grating(H, W, cycles):
    x = torch.linspace(0, 2*math.pi*cycles, W).view(1,1,1,W).expand(1,1,H,W)
    y = torch.linspace(0, 2*math.pi*cycles, H).view(1,1,H,1).expand(1,1,H,W)
    return 0.5*(torch.sin(x) + torch.sin(y)) * 0.5 + 0.5

@torch.no_grad()
def resolution_sweep(cycles_list=(2,4,6,8,10,12,14)):
    model.eval(); rows=[]
    for c in cycles_list:
        amp = make_sine_grating(64,64,c); phase = torch.zeros_like(amp)
        params = random_params(visibility=0.5, read_noise_std=0.01, background_level=0.01)
        holo = simulate_qhup_hologram(amp, phase, params).to(device)
        if holo.ndim == 5: holo = holo.squeeze(1)
        pred_amp, _ = model(holo)
        ssim_val = ssim_torchmetrics(pred_amp, amp.to(device)).item()
        rows.append({"cycles_per_64px": int(c), "ssim_amp": ssim_val})
        print(f"cycles={c:2d}  SSIM={ssim_val:.3f}")
    return rows

res_results = resolution_sweep()
with open(OUT/"metrics/resolution_sweep.csv", "w", newline="") as f:
    w = csv.DictWriter(f, fieldnames=["cycles_per_64px","ssim_amp"])
    w.writeheader(); w.writerows(res_results)

plt.figure(figsize=(5,4))
xs = [r["cycles_per_64px"] for r in res_results]
ys = [r["ssim_amp"] for r in res_results]
plt.plot(xs, ys, marker='o')
plt.xlabel("Spatial cycles (per 64 px)"); plt.ylabel("SSIM (amplitude)")
plt.title("Effective resolution vs spatial frequency"); plt.grid(True)
plt.tight_layout(); plt.savefig(OUT/"figs/resolution_sweep.png", dpi=150); plt.close()
print("Saved resolution sweep CSV and PNG to:", OUT/"metrics", "and", OUT/"figs")

# --- ZIP everything and auto-download ---
zip_name = "exports.zip"
if os.path.exists(zip_name):
    os.remove(zip_name)
shutil.make_archive("exports", "zip", root_dir=".", base_dir=str(OUT))
print("Created ZIP:", zip_name)

if IN_COLAB:
    files.download(zip_name)

# --- Final pointers ---
print("\nAll artifacts written under:", OUT.resolve())
print("ZIP includes:")
print("  - model weights, logs, metrics CSVs, visibility/resolution plots")
print("  - per-sample arrays (holo/amp_gt/amp_pred/phase_pred)")
print("  - individual PNGs + 4-up panel PNGs, multi-page PDF gallery, and a montage")